name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest  # Sá»­ dá»¥ng macOS vÃ¬ build iOS chá»‰ há»— trá»£ trÃªn macOS

    steps:
      # Check out mÃ£ nguá»“n tá»« repository
      - uses: actions/checkout@v3

      # CÃ i Ä‘áº·t Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # CÃ i Ä‘áº·t dependencies Flutter
      - run: flutter pub get

      # Cáº­p nháº­t Podfile Ä‘á»ƒ sá»­ dá»¥ng iOS 14
      - name: Update Podfile for iOS 14
        run: |
          sed -i '' 's/platform :ios, '12.0'/platform :ios, '14.0'/g' ios/Podfile
          cat ios/Podfile

      # Cáº­p nháº­t repository Pods
      - run: pod repo update
        working-directory: ios

      # CÃ i Ä‘áº·t Pods
      - run: pod install
        working-directory: ios

      # Build iOS app
      - run: flutter build ios --release --no-codesign

      # Táº¡o thÆ° má»¥c Payload
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Di chuyá»ƒn app vÃ o thÆ° má»¥c Payload
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # NÃ©n output thÃ nh .ipa
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Táº£i lÃªn báº£n phÃ¡t hÃ nh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
